### ISSUE TITLE
[咨询]函数方法复用

### ISSUE THREAD

**Issue by willin** [JacksonTian/fc-helper#3]
比如正常我们传统项目里会抽出一些 helper/utils 方法，model 模型之类的，在不同的路由、事件触发器等地方复用（通过代码文件拆分，然后 require）。

那么在云函数中，如何把一个个独立的函数也工程化，抽象封装的复用组件、方法该放到哪里，怎么调用？

**Comment by JacksonTian** [comment]
可以封装成普通的模块，require 即可。
